server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Agustin-debug/microservices-config-repo
          skipSslValidation: true
          clone-on-start: true
  eureka:
    instance:
      client:
        serviceUrl.defaultZone=http://localhost:8761/eureka/